window.FALLBACK_KNOWLEDGE = [
  {
    category: "科学",
    title: "天空不是蓝色颜料，而是光被选择性散射",
    summary: "太阳光进入大气后，波长较短的蓝光比红光更容易被空气分子向各个方向散射，所以白天从多数方向看去，天空呈现蓝色。",
    why: "它说明我们看到的颜色不仅取决于物体本身，也取决于光源、介质和观察位置。",
    prompt: "日落时太阳为什么更偏红？试着用“光走过的大气距离”解释。",
    sources: [{ name: "NASA Space Place", url: "https://spaceplace.nasa.gov/blue-sky/en/" }],
  },
  {
    category: "历史",
    title: "现代时区最初是铁路协调问题",
    summary: "在统一时区出现前，许多城镇按当地太阳位置计时。铁路发展后，不同地方时间让时刻表难以协调，推动了标准时间和时区制度。",
    why: "今天看似自然的时间制度，其实是技术网络扩大后，为降低协调成本而建立的规则。",
    prompt: "你每天使用的哪些“自然规则”，其实是为了解决大规模协作而设计的？",
    sources: [{ name: "NIST", url: "https://www.nist.gov/pml/time-and-frequency-division/popular-links/walk-through-time" }],
  },
  {
    category: "经济",
    title: "沉没成本不应决定下一步",
    summary: "沉没成本是已经发生且无法收回的成本。理性决策应比较从现在开始的未来收益与成本，而不是因为已经投入很多就继续投入。",
    why: "项目、购物、订阅和人际安排中，人很容易为了证明过去正确而增加未来损失。",
    prompt: "最近有没有一件事，你继续做的主要理由只是“已经花了很多时间或钱”？",
    sources: [{ name: "Encyclopaedia Britannica", url: "https://www.britannica.com/money/sunk-cost" }],
  },
  {
    category: "技术",
    title: "互联网和网页不是同一件事",
    summary: "互联网是连接网络与设备的基础设施；万维网是运行在互联网之上的一种信息系统，通过网址、HTTP和网页进行访问。",
    why: "区分基础设施和上层服务，有助于理解电子邮件、即时通信和网页为何都能使用互联网，却不是同一种产品。",
    prompt: "除了网页，你今天还使用了哪些运行在互联网之上的服务？",
    sources: [{ name: "CERN", url: "https://home.cern/science/computing/birth-web" }],
  },
  {
    category: "心理",
    title: "实施意图把愿望变成触发器",
    summary: "实施意图采用“如果发生X，我就做Y”的形式，把行动绑定到明确情境。它比只说“我要努力”更容易在关键时刻启动行为。",
    why: "固定触发器能减少临场选择，例如“下班后直接去健身房”比“今晚争取运动”更具体。",
    prompt: "为今天最重要的一件事写一句“如果……我就……”的行动规则。",
    sources: [{ name: "US National Library of Medicine", url: "https://pubmed.ncbi.nlm.nih.gov/12221980/" }],
  },
  {
    category: "健康",
    title: "体重的单日波动不等于脂肪变化",
    summary: "水分、盐分、碳水储存、进食时间和排便都会影响当天体重。观察一周平均值通常比解读某一个数字更可靠。",
    why: "用趋势代替单点判断，可以减少不必要的焦虑，也更容易坚持长期计划。",
    prompt: "本周平均体重与上周相比怎样，而不是今天与昨天相比怎样？",
    sources: [{ name: "CDC Healthy Weight", url: "https://www.cdc.gov/healthy-weight-growth/losing-weight/index.html" }],
  },
  {
    category: "地理",
    title: "地图上的面积会被投影方式改变",
    summary: "把球面地球展开到平面必然产生变形。常见的墨卡托投影便于航海定向，但会夸大靠近两极地区的面积。",
    why: "地图并非中性复制品；选择投影就是选择保留什么、牺牲什么。",
    prompt: "为什么格陵兰在很多地图上看起来和非洲差不多大，实际却小得多？",
    sources: [{ name: "USGS Map Projections", url: "https://pubs.usgs.gov/gip/70047422/report.pdf" }],
  },
  {
    category: "文化",
    title: "标点符号曾经不是写作的标准配置",
    summary: "古代文本常缺少现代意义上的空格和标点。随着朗读、抄写和印刷实践变化，标点逐渐成为帮助组织语义与节奏的系统。",
    why: "阅读习惯会被媒介塑造。今天习以为常的文字界面，也是长期演化出来的工具。",
    prompt: "如果一段工作邮件完全没有标点，你需要付出多少额外注意力？",
    sources: [{ name: "Encyclopaedia Britannica", url: "https://www.britannica.com/topic/punctuation" }],
  },
  {
    category: "科学",
    title: "冰浮在水上是一种少见的反常性质",
    summary: "多数物质的固态比液态密度更高，但水结冰时形成较疏松的晶格，使冰的密度低于液态水，因此能够漂浮。",
    why: "浮冰形成保温层，减缓水体继续冻结，对寒冷地区水生生态系统非常重要。",
    prompt: "如果冰会沉到底部，冬季湖泊的冻结过程会发生什么变化？",
    sources: [{ name: "USGS Water Science School", url: "https://www.usgs.gov/special-topics/water-science-school/science/water-density" }],
  },
  {
    category: "历史",
    title: "“铅笔芯”从来就不是铅",
    summary: "铅笔的书写材料主要是石墨与黏土的混合物。早期欧洲人曾误把石墨当成一种铅矿，名称和误解由此延续。",
    why: "日常语言会保留旧知识留下的痕迹，即使后来科学分类已经改变。",
    prompt: "你还知道哪些名字沿用了已经过时的理解？",
    sources: [{ name: "Smithsonian", url: "https://americanhistory.si.edu/collections/object-groups/pencils" }],
  },
  {
    category: "经济",
    title: "复利的力量同时作用于收益与费用",
    summary: "复利意味着每期收益加入本金后继续产生收益。同样，长期投资中看似很小的年度费用，也会持续减少可参与复利的本金。",
    why: "比较长期金融产品时，费率差异不能只看一年，而要看它对多年累计结果的影响。",
    prompt: "一项长期投资的费用率如果每年高1%，十年后会怎样影响结果？",
    sources: [{ name: "U.S. SEC Investor.gov", url: "https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator" }],
  },
  {
    category: "技术",
    title: "二维码的三个大方块用于定位",
    summary: "二维码角落的三个醒目方块是位置探测图形，帮助扫描设备识别二维码的方向、边界和旋转角度。",
    why: "好的机器可读设计会把定位、纠错与数据编码分开处理，从而提高现实环境中的可靠性。",
    prompt: "为什么二维码缺了一小部分有时仍能被识别？",
    sources: [{ name: "DENSO WAVE", url: "https://www.qrcode.com/en/about/" }],
  },
  {
    category: "心理",
    title: "选择越多，不一定越容易满意",
    summary: "更多选择有时能提高匹配度，但也会增加比较成本、后悔空间和决策拖延。效果取决于情境，而不是简单地“越少越好”。",
    why: "减少低价值选择，例如固定早餐或训练安排，可以把注意力留给真正需要判断的事情。",
    prompt: "你能否为一个每天重复的小决定设置默认选项？",
    sources: [{ name: "American Psychological Association", url: "https://www.apa.org/monitor/jun04/toomany" }],
  },
  {
    category: "健康",
    title: "力量训练不只是为了增加肌肉外观",
    summary: "规律力量训练有助于维持肌肉和骨骼、改善日常活动能力，并被公共健康指南列为成年人每周运动的重要组成部分。",
    why: "只做有氧运动可能忽略力量和功能性。稳定的每周两次训练比偶尔高强度更有价值。",
    prompt: "本周两次力量训练分别安排在哪一天、什么时间？",
    sources: [{ name: "CDC Physical Activity", url: "https://www.cdc.gov/physical-activity-basics/guidelines/adults.html" }],
  },
  {
    category: "地理",
    title: "河流弯道外侧通常侵蚀更强",
    summary: "弯曲河道中，水流速度和螺旋流动会让外侧河岸更容易受侵蚀，内侧则更容易沉积泥沙，弯道因此逐渐移动。",
    why: "地貌并非静止背景，而是水流、沉积物和时间共同形成的动态结果。",
    prompt: "观察卫星地图上的大河，你能找到弯道内侧的浅色沉积区域吗？",
    sources: [{ name: "USGS Water Science School", url: "https://www.usgs.gov/special-topics/water-science-school/science/rivers-streams-and-creeks" }],
  },
  {
    category: "文化",
    title: "博物馆标签也是一种压缩写作",
    summary: "一张优秀的展品标签要在有限字数内交代对象、背景与意义，同时避免把不确定的解释写成确定事实。",
    why: "这种写法与工作中的执行摘要相似：不是把资料缩短，而是保留最影响理解和判断的部分。",
    prompt: "能否用80字说明你当前项目最重要的风险、依据和下一步？",
    sources: [{ name: "Smithsonian Guidelines", url: "https://www.si.edu/mci/english-learners-and-museum-labels" }],
  },
];
